apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-app
  labels:
    app: java-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-sample-app
  template:
    metadata:
      labels:
        app: java-sample-app
    spec:
      containers:
      - name: java-sample-app
        image: william201192/java-sample-app:latest
        ports:
        - containerPort: 8080
