apiVersion: v1
kind: Service
metadata:
  name: java-sample-app-service
spec:
  type: LoadBalancer
  selector:
    app: java-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
